/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bowserf_nbody_CalculationNDK */

#ifndef _Included_com_bowserf_nbody_CalculationNDK
#define _Included_com_bowserf_nbody_CalculationNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bowserf_nbody_CalculationNDK
 * Method:    initializeValues
 * Signature: (IIIIFF)V
 */
JNIEXPORT jfloatArray JNICALL Java_com_bowserf_nbody_CalculationNDK_initializeValues
  (JNIEnv *, jobject, jint, jfloat, jint, jint, jfloat, jfloat);

/*
 * Class:     com_bowserf_nbody_CalculationNDK
 * Method:    computeNewPosition
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_bowserf_nbody_CalculationNDK_computeNewPosition
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
